apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:ZXSfFbV6SCIRXQEybA8P4OhMUzUwReBPdPJiIsEf9qh/dp9Mfr6jjw==,iv:500dnoPzshOVCDVfowyN/QEOHj/2vCtdSyoz99qg/w4=,tag:HU0W9loOxWnKn40XMnlrAw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13c9n5m7x26j4h0ykvp4ngc30a759r3xew9glu42w2z0w5ddyq5ks4qwgs9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2aWYrQ3JDTjh5aHEwbExs
            YStuSmc0KzRpRmxYNDRvRi93NW1FNGU4bG44CmtmS1k0TmFFcXRobGRVTDVXVVV6
            UHd5ck4zS1ZFT3J2d3B4WUQ3d2x0NFkKLS0tIGhhQ3gzdHNJd2JxYUt4U1BpMnRQ
            K0JuQ1Y2cWtyc0NaSUY3NFRoQTZWWjAKc67IU+fnv43iqA21GxZa6v4Yuqc3aMjx
            aaUHDAEKu34o0e0V/ajcrVQ/wUfjWlt8nRhC9ntfx+X/0NmjCcbmkw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-21T18:22:00Z"
    mac: ENC[AES256_GCM,data:JAvLLvHLPLor2yrKTKTpI5geGX+FxJ3Mni6nNsMND6Eq18fUMeMI0yvy51FUgCkpUvpxxxyN+ekGdSNhH4nmoejsn6VzuzTFem4GZuwFH79EeR0b8oHossedZrO3gJzcHjQW6+7DFPAey1q8SdqcsAQDg9MgvH1P6rh5qFkwEwk=,iv:PkFBvCf+gfSahkTyjtr4diVoAG7InHAdMsiRPC8UiOE=,tag:l/JWAEuaMzyxUXUGQbMK8g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
