apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:IJwQ7g9jdzcW,iv:TiKY+t4LmIT28GVJSa3xqpZNUneF1JU9sT+CF2xzY/8=,tag:cvM4HcXNWjaU7QpZg2vORQ==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:6tzeg1RBPwcH4MELrffMpMlSM+5p+gpV,iv:0YHelHohbiRDRP1N3KyLoV+sa/KHxrcCFTKeTct2Ya0=,tag:Y2rjotBB9JFpyT2oWOTUFQ==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:rzsP8dBJK7rDzdc56oR4FCANKKoZgGs1lDOF1TiyX/GLabIN,iv:bjnb/IeNdk6eUDcuPPnPOkkGyEn1KTq/4mbYRo7COvw=,tag:ErneqsXsSAUYUgCNAv7EYg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13c9n5m7x26j4h0ykvp4ngc30a759r3xew9glu42w2z0w5ddyq5ks4qwgs9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsdTMxRThyeld5ay9HMUx1
            ZzF0ZE5xbnBDdExWeHFxSjJSVmkva0orQWk0CnA3YUxOeXF0dTY0UjErdk9XaHBX
            YUU3ZWMwVXZNTEZyY3pGNy9wUmJMZDAKLS0tIDhmNnEyOUM4Tk5Bb2wwNFFFMU1G
            cmhleTA1UTdkNngvOWc3MW5ieHozbHcKoeNPHnM+AWqFCx4Ap2ME5yt3Fc4DuTqH
            hTlHo+nNgglxdkSKRxD/idQICxBFUDWo/tmH5l+t7A7hfx0DndFGvw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-21T18:22:01Z"
    mac: ENC[AES256_GCM,data:7E+sTE3Yt+u7U/2SN6EpYguLch8hlHyUNEtonMzDmVO7WNBor1vCThZwIhzDqvoN7Kgl3a0p+wtWxfa+YZchQETI5ZCALmdAaMoUBUrAZZPeVrrdlXiDMeXbEy+vuBwwTL9WTjDMRz9DQUiDQVIse3sdgQDHp9sjZndSXn6thWA=,iv:chGfbyfVAd359KhCzOYx9ZDNJr36e0xRZqxs0ejNBDg=,tag:+5GCWv7FDKBFCFKFrpO+dQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
